version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=codeshare
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d codeshare"]
      interval: 5s
      retries: 10
      start_period: 5s
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      retries: 10
      start_period: 5s
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=password
    networks:
      - backend
  
  web:
    image: paraspunjabi2002/codeshare:latest
    container_name : web
    ports:
      - "8000:8000"  
    environment:
      - DATABASE_URL=postgresql://root:password@postgres:5432/codeshare
      - PORT=8000
      - REDIS_URL=redis://:password@redis:6379
      - TIME_PERIOD=2592000  
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend
    
networks:
  backend:
    driver: bridge

volumes:
  postgres_data: